[package]
name = "sthil-chainsaw-schreensaver-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies] 
thiserror = "1.0.37"
iced = { version = "0.4", features = ["svg"] }
rgb = "0.8"